version: "3"
services:
    transactions:
        container_name: transactions
        build: .
        links:
          - db
    db:
        container_name: db
        image: postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: transactions