version: "3"
services:
    transactions:
        container_name: transactions
        build: .
        links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        restart: unless-stopped
        command: 
            - '--logpath'
            - '/var/log/mongodb/mongod.log'
        ports:
            - '27018:27017'