export interface ITransaction {
  amount: Number,
  txid: String,
  involvesWatchonly: Boolean,
  account: String,
  address: String,
  category: String,
  label: String,
  confirmations: Number,
  blockhash: String,
  blockindex: Number,
  blocktime: number,
  vout: Number,
  walletconflicts: Array<String> | string,
  time: number,
  timereceived: number,
}